name: native_video_player
description: A Flutter widget to play videos on iOS and Android using a native implementation.
version: 2.0.0
repository: https://github.com/albemala/native_video_player

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  path: ^1.9.0

  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0

  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  plugin:
    platforms:
      android:
        package: me.albemala.native_video_player
        pluginClass: NativeVideoPlayerPlugin
      ios:
        pluginClass: NativeVideoPlayerPlugin
